import { Card } from '../models/card.model';
import { CardType, Difficulty, Race } from '../models/race.model';

export const UD_BUILDINGS: Card[] = [
  {
    id: 'ud_temple_of_the_damned',
    name: 'Temple of the Damned',
    race: Race.Undead,
    type: CardType.Building,
    goldCost: 155,
    woodCost: 140,
    imagePath: 'assets/images/buildings/Templeofthedamned.png',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ud_necropolis',
    name: 'Necropolis',
    race: Race.Undead,
    type: CardType.Building,
    goldCost: 320,
    woodCost: 0,
    imagePath: 'assets/images/buildings/NecropolisWCIII.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ud_halls_of_the_dead',
    name: 'Halls of the Dead',
    race: Race.Undead,
    type: CardType.Building,
    goldCost: 320,
    woodCost: 210,
    imagePath: 'assets/images/buildings/Halls_of_the_Dead.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ud_black_citadel',
    name: 'Black Citadel',
    race: Race.Undead,
    type: CardType.Building,
    goldCost: 325,
    woodCost: 230,
    imagePath: 'assets/images/buildings/Black_Citadel.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ud_crypt',
    name: 'Crypt',
    race: Race.Undead,
    type: CardType.Building,
    goldCost: 200,
    woodCost: 50,
    imagePath: 'assets/images/buildings/Crypt.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ud_graveyard',
    name: 'Graveyard',
    race: Race.Undead,
    type: CardType.Building,
    goldCost: 215,
    woodCost: 0,
    imagePath: 'assets/images/buildings/Graveyard.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ud_ziggurat',
    name: 'Ziggurat',
    race: Race.Undead,
    type: CardType.Building,
    goldCost: 150,
    woodCost: 50,
    imagePath: 'assets/images/buildings/Ziggurat.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ud_spirit_tower',
    name: 'Spirit Tower',
    race: Race.Undead,
    type: CardType.Building,
    goldCost: 145,
    woodCost: 40,
    imagePath: 'assets/images/buildings/Spirit_Tower.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ud_altar_of_darkness',
    name: 'Altar of Darkness',
    race: Race.Undead,
    type: CardType.Building,
    goldCost: 180,
    woodCost: 50,
    imagePath: 'assets/images/buildings/Altarofdarkness.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ud_slaughterhouse',
    name: 'Slaughterhouse',
    race: Race.Undead,
    type: CardType.Building,
    goldCost: 140,
    woodCost: 135,
    imagePath: 'assets/images/buildings/Slaughterhouse.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ud_sacrificial_pit',
    name: 'Sacrificial Pit',
    race: Race.Undead,
    type: CardType.Building,
    goldCost: 75,
    woodCost: 150,
    imagePath: 'assets/images/buildings/Sacrificialpit.jpg',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ud_boneyard',
    name: 'Boneyard',
    race: Race.Undead,
    type: CardType.Building,
    goldCost: 175,
    woodCost: 200,
    imagePath: 'assets/images/buildings/Boneyard.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ud_tomb_of_relics',
    name: 'Tomb of Relics',
    race: Race.Undead,
    type: CardType.Building,
    goldCost: 130,
    woodCost: 30,
    imagePath: 'assets/images/buildings/Tomb_of_Relics.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ud_nerubian_tower',
    name: 'Nerubian Tower',
    race: Race.Undead,
    type: CardType.Building,
    goldCost: 100,
    woodCost: 20,
    imagePath: 'assets/images/buildings/Nerubian_Tower.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ud_haunted_gold_mine',
    name: 'Haunted Gold Mine',
    race: Race.Undead,
    type: CardType.Building,
    goldCost: 255,
    woodCost: 200,
    imagePath: 'assets/images/buildings/Haunted_Goldmine.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
];

export const HU_BUILDINGS: Card[] = [
  {
    id: 'hu_town_hall',
    name: 'Town Hall',
    race: Race.Human,
    type: CardType.Building,
    goldCost: 385,
    woodCost: 205,
    imagePath: 'assets/images/buildings/Townhall-red.jpg',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'hu_keep',
    name: 'Keep',
    race: Race.Human,
    type: CardType.Building,
    goldCost: 320,
    woodCost: 210,
    imagePath: 'assets/images/buildings/Keep-red.jpg',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'hu_castle',
    name: 'Castle',
    race: Race.Human,
    type: CardType.Building,
    goldCost: 360,
    woodCost: 210,
    imagePath: 'assets/images/buildings/Castle-red.jpg',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'hu_barracks',
    name: 'Barracks',
    race: Race.Human,
    type: CardType.Building,
    goldCost: 160,
    woodCost: 60,
    imagePath: 'assets/images/buildings/HumBarracks.jpg',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'hu_farm',
    name: 'Farm',
    race: Race.Human,
    type: CardType.Building,
    goldCost: 80,
    woodCost: 20,
    imagePath: 'assets/images/buildings/Farm.jpg',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'hu_altar_of_kings',
    name: 'Altar of Kings',
    race: Race.Human,
    type: CardType.Building,
    goldCost: 180,
    woodCost: 50,
    imagePath: 'assets/images/buildings/Altar_of_Kings.jpg',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'hu_lumber_mill',
    name: 'Lumber Mill',
    race: Race.Human,
    type: CardType.Building,
    goldCost: 120,
    woodCost: 0,
    imagePath: 'assets/images/buildings/Lumber_Mill.jpg',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'hu_scout_tower',
    name: 'Scout Tower',
    race: Race.Human,
    type: CardType.Building,
    goldCost: 30,
    woodCost: 20,
    imagePath: 'assets/images/buildings/Scout_Tower.jpg',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'hu_guard_tower',
    name: 'Guard Tower',
    race: Race.Human,
    type: CardType.Building,
    goldCost: 70,
    woodCost: 50,
    imagePath: 'assets/images/buildings/Guard_Tower.jpg',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'hu_cannon_tower',
    name: 'Cannon Tower',
    race: Race.Human,
    type: CardType.Building,
    goldCost: 170,
    woodCost: 100,
    imagePath: 'assets/images/buildings/Cannon_Tower.jpg',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'hu_arcane_tower',
    name: 'Arcane Tower',
    race: Race.Human,
    type: CardType.Building,
    goldCost: 70,
    woodCost: 50,
    imagePath: 'assets/images/buildings/Arcane_Tower.jpg',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'hu_blacksmith',
    name: 'Blacksmith',
    race: Race.Human,
    type: CardType.Building,
    goldCost: 140,
    woodCost: 60,
    imagePath: 'assets/images/buildings/Blacksmith.jpg',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'hu_workshop',
    name: 'Workshop',
    race: Race.Human,
    type: CardType.Building,
    goldCost: 140,
    woodCost: 140,
    imagePath: 'assets/images/buildings/Workshop.jpg',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'hu_arcane_sanctum',
    name: 'Arcane Sanctum',
    race: Race.Human,
    type: CardType.Building,
    goldCost: 150,
    woodCost: 140,
    imagePath: 'assets/images/buildings/Arcane_Sanctum.jpg',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'hu_gryphon_aviary',
    name: 'Gryphon Aviary',
    race: Race.Human,
    type: CardType.Building,
    goldCost: 140,
    woodCost: 150,
    imagePath: 'assets/images/buildings/Gryphon_Aviary.jpg',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'hu_arcane_vault',
    name: 'Arcane Vault',
    race: Race.Human,
    type: CardType.Building,
    goldCost: 130,
    woodCost: 30,
    imagePath: 'assets/images/buildings/Arcane_Vault.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
];

export const NE_BUILDINGS: Card[] = [
  {
    id: 'ne_tree_of_life',
    name: 'Tree of Life',
    race: Race.NightElf,
    type: CardType.Building,
    goldCost: 340,
    woodCost: 185,
    imagePath: 'assets/images/buildings/Treeoflife.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ne_tree_of_ages',
    name: 'Tree of Ages',
    race: Race.NightElf,
    type: CardType.Building,
    goldCost: 320,
    woodCost: 180,
    imagePath: 'assets/images/buildings/Treeofages.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ne_tree_of_eternity',
    name: 'Tree of Eternity',
    race: Race.NightElf,
    type: CardType.Building,
    goldCost: 330,
    woodCost: 200,
    imagePath: 'assets/images/buildings/Treeofeternity.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ne_ancient_of_war',
    name: 'Ancient of War',
    race: Race.NightElf,
    type: CardType.Building,
    goldCost: 150,
    woodCost: 60,
    imagePath: 'assets/images/buildings/Ancientofwar.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ne_ancient_of_lore',
    name: 'Ancient of Lore',
    race: Race.NightElf,
    type: CardType.Building,
    goldCost: 155,
    woodCost: 145,
    imagePath: 'assets/images/buildings/Ancientoflore.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ne_ancient_of_wind',
    name: 'Ancient of Wind',
    race: Race.NightElf,
    type: CardType.Building,
    goldCost: 150,
    woodCost: 140,
    imagePath: 'assets/images/buildings/Ancientofwind.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ne_ancient_of_wonders',
    name: 'Ancient of Wonders',
    race: Race.NightElf,
    type: CardType.Building,
    goldCost: 180,
    woodCost: 40,
    imagePath: 'assets/images/buildings/Ancientofwonder.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ne_moon_well',
    name: 'Moon Well',
    race: Race.NightElf,
    type: CardType.Building,
    goldCost: 320,
    woodCost: 210,
    imagePath: 'assets/images/buildings/Moonwell.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ne_altar_of_elders',
    name: 'Altar of Elders',
    race: Race.NightElf,
    type: CardType.Building,
    goldCost: 360,
    woodCost: 210,
    imagePath: 'assets/images/buildings/Altar_of_Elders.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ne_hunters_hall',
    name: "Hunter's Hall",
    race: Race.NightElf,
    type: CardType.Building,
    goldCost: 210,
    woodCost: 100,
    imagePath: 'assets/images/buildings/Hunters_Hall.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ne_chimaera_roost',
    name: 'Chimaera Roost',
    race: Race.NightElf,
    type: CardType.Building,
    goldCost: 140,
    woodCost: 190,
    imagePath: 'assets/images/buildings/Chimaera_Roost.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ne_ancient_protector',
    name: 'Ancient Protector',
    race: Race.NightElf,
    type: CardType.Building,
    goldCost: 135,
    woodCost: 80,
    imagePath: 'assets/images/buildings/Ancientprotector.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  }
];

export const OC_BUILDINGS: Card[] = [
  {
    id: 'oc_great_hall',
    name: 'Great Hall',
    race: Race.Orc,
    type: CardType.Building,
    goldCost: 385,
    woodCost: 185,
    imagePath: 'assets/images/buildings/Great_Hall.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'oc_stronghold',
    name: 'Stronghold',
    race: Race.Orc,
    type: CardType.Building,
    goldCost: 315,
    woodCost: 190,
    imagePath: 'assets/images/buildings/Stronghold.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'oc_fortress',
    name: 'Fortress',
    race: Race.Orc,
    type: CardType.Building,
    goldCost: 325,
    woodCost: 190,
    imagePath: 'assets/images/buildings/Fortress.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'oc_barracks',
    name: 'Barracks',
    race: Race.Orc,
    type: CardType.Building,
    goldCost: 180,
    woodCost: 50,
    imagePath: 'assets/images/buildings/Barracks.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'oc_war_mill',
    name: 'War Mill',
    race: Race.Orc,
    type: CardType.Building,
    goldCost: 205,
    woodCost: 0,
    imagePath: 'assets/images/buildings/War_Mill.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'oc_burrow',
    name: 'Orc Burrow',
    race: Race.Orc,
    type: CardType.Building,
    goldCost: 160,
    woodCost: 40,
    imagePath: 'assets/images/buildings/Orc_Burrow.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'oc_altar_of_storms',
    name: 'Altar of Storms',
    race: Race.Orc,
    type: CardType.Building,
    goldCost: 180,
    woodCost: 50,
    imagePath: 'assets/images/buildings/Altarofstorms.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'oc_watch_tower',
    name: 'Watch Tower',
    race: Race.Orc,
    type: CardType.Building,
    goldCost: 110,
    woodCost: 80,
    imagePath: 'assets/images/buildings/Watch_Tower.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'oc_spirit_lodge',
    name: 'Spirit Lodge',
    race: Race.Orc,
    type: CardType.Building,
    goldCost: 150,
    woodCost: 150,
    imagePath: 'assets/images/buildings/Spirit_Lodge.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'oc_beastiary',
    name: 'Beastiary',
    race: Race.Orc,
    type: CardType.Building,
    goldCost: 145,
    woodCost: 140,
    imagePath: 'assets/images/buildings/Beastiary.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'oc_tauren_totem',
    name: 'Tauren Totem',
    race: Race.Orc,
    type: CardType.Building,
    goldCost: 135,
    woodCost: 155,
    imagePath: 'assets/images/buildings/Tauren_Totem.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'oc_voodoo_lounge',
    name: 'Voodoo Lounge',
    race: Race.Orc,
    type: CardType.Building,
    goldCost: 130,
    woodCost: 30,
    imagePath: 'assets/images/buildings/Voodoo_Lounge.gif',
    difficulty: [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard],
  },
];
