// src/app/services/game-data.service.ts
import { Injectable } from '@angular/core';
import { Card } from '../models/card.model';
import { CardType, Difficulty, Race } from '../models/race.model';

@Injectable({
  providedIn: 'root',
})
export class GameDataService {
  private cards: Card[] = [
    // ALL UPGRADES
    // Undead Upgrades
    {
      id: 'ud_unholy_strength',
      name: 'Unholy Strength',
      race: Race.Undead,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNUnholyStrength.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ud_improved_unholy_strength',
      name: 'Improved Unholy Strength',
      race: Race.Undead,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNImprovedUnholyStrength.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ud_advanced_unholy_strength',
      name: 'Advanced Unholy Strength',
      race: Race.Undead,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNAdvancedUnholyStrength.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ud_creature_attack',
      name: 'Creature Attack',
      race: Race.Undead,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNCreatureAttack.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ud_improved_creature_attack',
      name: 'Improved Creature Attack',
      race: Race.Undead,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNImprovedCreatureAttack.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ud_advanced_creature_attack',
      name: 'Advanced Creature Attack',
      race: Race.Undead,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNAdvancedCreatureAttack.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ud_unholy_armor',
      name: 'Unholy Armor',
      race: Race.Undead,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNUnholyArmor.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ud_improved_unholy_armor',
      name: 'Improved Unholy Armor',
      race: Race.Undead,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNImprovedUnholyArmor.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ud_advanced_unholy_armor',
      name: 'Advanced Unholy Armor',
      race: Race.Undead,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNAdvancedUnholyArmor.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ud_creature_carapace',
      name: 'Creature Carapace',
      race: Race.Undead,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNCreatureCarapace.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ud_improved_creature_carapace',
      name: 'Improved Creature Carapace',
      race: Race.Undead,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNImprovedCreatureCarapace.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ud_advanced_creature_carapace',
      name: 'Advanced Creature Carapace',
      race: Race.Undead,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNAdvancedCreatureCarapace.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ud_necromancer_adept_training',
      name: 'Necromancer Adept Training',
      race: Race.Undead,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNNecromancerAdept.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ud_necromancer_master_training',
      name: 'Necromancer Master Training',
      race: Race.Undead,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNNecromancerMaster.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ud_banshee_adept_training',
      name: 'Banshee Adept Training',
      race: Race.Undead,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNBansheeAdept.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ud_banshee_master_training',
      name: 'Banshee Master Training',
      race: Race.Undead,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNBansheeMaster.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ud_cannibalize',
      name: 'Cannibalize',
      race: Race.Undead,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Cannibalize.gif',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ud_ghoul_frenzy',
      name: 'Ghoul Frenzy',
      race: Race.Undead,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNGhoulFrenzy.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ud_web',
      name: 'Web',
      race: Race.Undead,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Web.gif',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ud_burrow',
      name: 'Burrow',
      race: Race.Undead,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Cryptfiendburrow.gif',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ud_stone_form',
      name: 'Stone Form',
      race: Race.Undead,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Stoneform.gif',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ud_skeletal_mastery',
      name: 'Skeletal Mastery',
      race: Race.Undead,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNSkeletonMage.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ud_disease_cloud',
      name: 'Disease Cloud',
      race: Race.Undead,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Plaguecloud.gif',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ud_exhume_corpses',
      name: 'Exhume Corpses',
      race: Race.Undead,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3PASBTNExhumeCorpses.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ud_destroyer_form',
      name: 'Destroyer Form',
      race: Race.Undead,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Destroyer.gif',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ud_freezing_breath',
      name: 'Freezing Breath',
      race: Race.Undead,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Freezingbreath2.gif',
      difficulty: [Difficulty.Hard],
    },

    // Human Upgrades
    {
      id: 'hu_improved_masonry',
      name: 'Improved Masonry',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNStoneArchitecture.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_advanced_masonry',
      name: 'Advanced Masonry',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNArcaniteArchitecture.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_imbued_masonry',
      name: 'Imbued Masonry',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNImbuedMasonry.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_magic_sentry',
      name: 'Magic Sentry',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3PASBTNMagicalSentry.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_fragmentation_shards',
      name: 'Fragmentation Shards',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Fragmentationshards.gif',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_iron_forged_swords',
      name: 'Iron Forged Swords',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNSteelMelee.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_steel_forged_swords',
      name: 'Steel Forged Swords',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNThoriumMelee.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_mithril_forged_swords',
      name: 'Mithril Forged Swords',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNArcaniteMelee.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_black_gunpowder',
      name: 'Black Gunpowder',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNHumanMissileUpOne.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_refined_gunpowder',
      name: 'Refined Gunpowder',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNHumanMissileUpTwo.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_imbued_gunpowder',
      name: 'Imbued Gunpowder',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNHumanMissileUpThree.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_iron_plating',
      name: 'Iron Plating',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNHumanArmorUpOne.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_steel_plating',
      name: 'Steel Plating',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNHumanArmorUpTwo.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_mithril_plating',
      name: 'Mithril Plating',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNHumanArmorUpThree.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_studded_leather_armor',
      name: 'Studded Leather Armor',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNLeatherUpgradeOne.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_reinforced_leather_armor',
      name: 'Reinforced Leather Armor',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNLeatherUpgradeTwo.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_dragonhide_armor',
      name: 'Dragonhide Armor',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNLeatherUpgradeThree.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_priest_adept_training',
      name: 'Priest Adept Training',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNPriestAdept.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_priest_master_training',
      name: 'Priest Master Training',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNPriestMaster.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_sorceress_adept_training',
      name: 'Sorceress Adept Training',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNSorceressAdept.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_sorceress_master_training',
      name: 'Sorceress Master Training',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNSorceressMaster.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_defend',
      name: 'Defend',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Defend.gif',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_long_rifles',
      name: 'Long Rifles',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNDwarvenLongRifle.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_control_magic',
      name: 'Control Magic',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Controlmagic.gif',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_flak_cannons',
      name: 'Flak Cannons',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3PASBTNFlakCannons.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_flying_machine_bombs',
      name: 'Flying Machine Bombs',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNHumanArtilleryUpOne.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_flare',
      name: 'Flare',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Flare.gif',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_animal_war_training',
      name: 'Animal War Training',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNAnimalWarTraining.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_cloud',
      name: 'Cloud',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Cloud.gif',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_sundering_blades',
      name: 'Sundering Blades',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3PASBTNSunderingBlades.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_barrage',
      name: 'Barrage',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Barrage.gif',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'hu_storm_hammers',
      name: 'Storm Hammers',
      race: Race.Human,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Stormhammer.gif',
      difficulty: [Difficulty.Hard],
    },

    // Night Elf Upgrades
    {
      id: 'ne_natures_blessing',
      name: "Nature's Blessing",
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNNaturesBlessing.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_well_spring',
      name: 'Well Spring',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNwellspring.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_strength_of_the_moon',
      name: 'Strength of the Moon',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNStrengthOfTheMoon.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_improved_strength_of_the_moon',
      name: 'Improved Strength of the Moon',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNImprovedStrengthOfTheMoon.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_advanced_strength_of_the_moon',
      name: 'Advanced Strength of the Moon',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNAdvancedStrengthOfTheMoon.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_strength_of_the_wild',
      name: 'Strength of the Wild',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNStrengthOfTheWild.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_improved_strength_of_the_wild',
      name: 'Improved Strength of the Wild',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNImprovedStrengthOfTheWild.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_advanced_strength_of_the_wild',
      name: 'Advanced Strength of the Wild',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNAdvancedStrengthOfTheWild.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_moon_armor',
      name: 'Moon Armor',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNMoonArmor.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_improved_moon_armor',
      name: 'Improved Moon Armor',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNImprovedMoonArmor.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_advanced_moon_armor',
      name: 'Advanced Moon Armor',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNAdvancedMoonArmor.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_reinforced_hides',
      name: 'Reinforced Hides',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNReinforcedHides.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_improved_reinforced_hides',
      name: 'Improved Reinforced Hides',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNImprovedReinforcedHides.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_advanced_reinforced_hides',
      name: 'Advanced Reinforced Hides',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNAdvancedReinforcedHides.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_druid_of_the_talon_adept_training',
      name: 'Druid of the Talon Adept Training',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNDOTAdeptTraining.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_druid_of_the_talon_master_training',
      name: 'Druid of the Talon Master Training',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNDOTMasterTraining.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_druid_of_the_claw_adept_training',
      name: 'Druid of the Claw Adept Training',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNDOCAdeptTraining.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_druid_of_the_claw_master_training',
      name: 'Druid of the Claw Master Training',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNDOCMasterTraining.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_improved_bows',
      name: 'Improved Bows',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNImprovedBows.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_marksmanship',
      name: 'Marksmanship',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNMarksmanship.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_sentinel',
      name: 'Sentinel',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Sentinelability.gif',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_moon_glaive',
      name: 'Moon Glaive',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Moonglaive.gif',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_vorpal_blades',
      name: 'Vorpal Blades',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Vorpalblades.gif',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_mark_of_the_talon',
      name: 'Mark of the Talon',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Faeriefire.gif',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_abolish_magic',
      name: 'Abolish Magic',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 50,
      woodCost: 50,
      imagePath: 'assets/images/cards/45px-AbolishMagic.gif',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_mark_of_the_claw',
      name: 'Mark of the Claw',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNEnchantedbears.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_resistant_skin',
      name: 'Resistant Skin',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3PASBTNResistantSkin.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_hardened_skin',
      name: 'Hardened Skin',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3PASBTNHardenedSkin.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_corrosive_breath',
      name: 'Corrosive Breath',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Corrosivebreath2.gif',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'ne_ultravision',
      name: 'Ultravision',
      race: Race.NightElf,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNultravision.png',
      difficulty: [Difficulty.Hard],
    },
    // Orc Upgrades
    {
      id: 'orc_spiked_barricades',
      name: 'Spiked Barricades',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNSpikedBarricades.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'orc_improved_spiked_barricades',
      name: 'Improved Spiked Barricades',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNImprovedSpikedBarricades.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'orc_reinforced_defenses',
      name: 'Reinforced Defenses',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNReinforcedBurrows.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'orc_steel_melee_weapons',
      name: 'Steel Melee Weapons',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNOrcMeleeUpOne.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'orc_thorium_melee_weapons',
      name: 'Thorium Melee Weapons',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNOrcMeleeUpTwo.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'orc_arcanite_melee_weapons',
      name: 'Arcanite Melee Weapons',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNOrcMeleeUpThree.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'orc_steel_ranged_weapons',
      name: 'Steel Ranged Weapons',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNSteelRanged.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'orc_thorium_ranged_weapons',
      name: 'Thorium Ranged Weapons',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNThoriumRanged.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'orc_arcanite_ranged_weapons',
      name: 'Arcanite Ranged Weapons',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNArcaniteRanged.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'orc_steel_armor',
      name: 'Steel Armor',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNSteelArmor.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'orc_thorium_armor',
      name: 'Thorium Armor',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNThoriumArmor.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'orc_arcanite_armor',
      name: 'Arcanite Armor',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNArcaniteArmor.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'orc_shaman_adept_training',
      name: 'Shaman Adept Training',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNShamanAdept.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'orc_shaman_master_training',
      name: 'Shaman Master Training',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNShamanMaster.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'orc_witch_doctor_adept_training',
      name: 'Witch Doctor Adept Training',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNWitchDoctorAdept.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'orc_witch_doctor_master_training',
      name: 'Witch Doctor Master Training',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNWitchDoctorMaster.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'orc_spirit_walker_adept_training',
      name: 'Spirit Walker Adept Training',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNSpiritWalkerAdeptTraining.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'orc_spirit_walker_master_training',
      name: 'Spirit Walker Master Training',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath:
        'assets/images/cards/45px-Wc3BTNSpiritWalkerMasterTraining.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'orc_pillage',
      name: 'Pillage',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Pillage.gif',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'orc_brute_strength',
      name: 'Brute Strength',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNBerserk.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'orc_troll_regeneration',
      name: 'Troll Regeneration',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNRegenerate.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'orc_berserker_upgrade',
      name: 'Berserker Upgrade',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNHeadHunterBerserker.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'orc_burning_oil',
      name: 'Burning Oil',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Naphtha.gif',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'orc_ensnare',
      name: 'Ensnare',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Ensnareability.gif',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'orc_envenomed_spears',
      name: 'Envenomed Spears',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Envenomedspears.gif',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'orc_war_drums_damage_increase',
      name: 'War Drums Damage Increase',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNDrum.png',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'orc_liquid_fire',
      name: 'Liquid Fire',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Liquidfire.gif',
      difficulty: [Difficulty.Hard],
    },
    {
      id: 'orc_pulverize_damage_increase',
      name: 'Pulverize Damage Increase',
      race: Race.Orc,
      type: CardType.Upgrade,
      goldCost: 0,
      woodCost: 0,
      imagePath: 'assets/images/cards/45px-Wc3BTNSmash.png',
      difficulty: [Difficulty.Hard],
    },
  ];

  constructor() {
    const names = this.cards.map(c => c.name);
    console.log('names: ');
    console.log(names);
    
    
  }

  getCardsByRace(race: Race): Card[] {
    return this.cards.filter((card) => card.race === race);
  }

  getCardsByRaceAndDifficulty(race: Race, difficulty: Difficulty): Card[] {
    return this.cards.filter(
      (card) => card.race === race && card.difficulty.includes(difficulty)
    );
  }

  getCardsByRaceAndType(race: Race, type: CardType): Card[] {
    return this.cards.filter(
      (card) => card.race === race && card.type === type
    );
  }
}
