export const cardNames = [
  "Unholy Strength",
  "Improved Unholy Strength",
  "Advanced Unholy Strength",
  "Creature Attack",
  "Improved Creature Attack",
  "Advanced Creature Attack",
  "Unholy Armor",
  "Improved Unholy Armor",
  "Advanced Unholy Armor",
  "Creature Carapace",
  "Improved Creature Carapace",
  "Advanced Creature Carapace",
  "Necromancer Adept Training",
  "Necromancer Master Training",
  "Banshee Adept Training",
  "Banshee Master Training",
  "Cannibalize",
  "Ghoul Frenzy",
  "Web",
  "Burrow",
  "Stone Form",
  "Skeletal Mastery",
  "Disease Cloud",
  "Exhume Corpses",
  "Destroyer Form",
  "Freezing Breath",
  "Improved Masonry",
  "Advanced Masonry",
  "Imbued Masonry",
  "Magic Sentry",
  "Fragmentation Shards",
  "Iron Forged Swords",
  "Steel Forged Swords",
  "Mithril Forged Swords",
  "Black Gunpowder",
  "Refined Gunpowder",
  "Imbued Gunpowder",
  "Iron Plating",
  "Steel Plating",
  "Mithril Plating",
  "Studded Leather Armor",
  "Reinforced Leather Armor",
  "Dragonhide Armor",
  "Priest Adept Training",
  "Priest Master Training",
  "Sorceress Adept Training",
  "Sorceress Master Training",
  "Defend",
  "Long Rifles",
  "Control Magic",
  "Flak Cannons",
  "Flying Machine Bombs",
  "Flare",
  "Animal War Training",
  "Cloud",
  "Sundering Blades",
  "Barrage",
  "Storm Hammers",
  "Nature's Blessing",
  "Well Spring",
  "Strength of the Moon",
  "Improved Strength of the Moon",
  "Advanced Strength of the Moon",
  "Strength of the Wild",
  "Improved Strength of the Wild",
  "Advanced Strength of the Wild",
  "Moon Armor",
  "Improved Moon Armor",
  "Advanced Moon Armor",
  "Reinforced Hides",
  "Improved Reinforced Hides",
  "Advanced Reinforced Hides",
  "Druid of the Talon Adept Training",
  "Druid of the Talon Master Training",
  "Druid of the Claw Adept Training",
  "Druid of the Claw Master Training",
  "Improved Bows",
  "Marksmanship",
  "Sentinel",
  "Moon Glaive",
  "Vorpal Blades",
  "Mark of the Talon",
  "Abolish Magic",
  "Mark of the Claw",
  "Resistant Skin",
  "Hardened Skin",
  "Corrosive Breath",
  "Ultravision",
  "Spiked Barricades",
  "Improved Spiked Barricades",
  "Reinforced Defenses",
  "Steel Melee Weapons",
  "Thorium Melee Weapons",
  "Arcanite Melee Weapons",
  "Steel Ranged Weapons",
  "Thorium Ranged Weapons",
  "Arcanite Ranged Weapons",
  "Steel Armor",
  "Thorium Armor",
  "Arcanite Armor",
  "Shaman Adept Training",
  "Shaman Master Training",
  "Witch Doctor Adept Training",
  "Witch Doctor Master Training",
  "Spirit Walker Adept Training",
  "Spirit Walker Master Training",
  "Pillage",
  "Brute Strength",
  "Troll Regeneration",
  "Berserker Upgrade",
  "Burning Oil",
  "Ensnare",
  "Envenomed Spears",
  "War Drums Damage Increase",
  "Liquid Fire",
  "Pulverize Damage Increase"
];
