// from https://wowpedia.fandom.com/wiki/Warcraft_III_units
import { Card } from "./models/card.model";
import { CardType, Difficulty, Race } from "./models/race.model";

export const UD_UNITS: Card[] = [
  {
    id: 'ud_acolyte',
    name: 'Acolyte',
    race: Race.Undead,
    type: CardType.Unit,
    goldCost: 75,
    woodCost: 0,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/5/53/BTNAcolyte.png/revision/latest?cb=20210516213617',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ud_ghoul',
    name: 'Ghoul',
    race: Race.Undead,
    type: CardType.Unit,
    goldCost: 120,
    woodCost: 0,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/9/95/BTNGhoul.png/revision/latest?cb=20090112004332',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ud_abomination',
    name: 'Abomination',
    race: Race.Undead,
    type: CardType.Unit,
    goldCost: 240,
    woodCost: 70,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/7/70/BTNAbomination.png/revision/latest?cb=20210516213523',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ud_meat_wagon',
    name: 'Meat Wagon',
    race: Race.Undead,
    type: CardType.Unit,
    goldCost: 230,
    woodCost: 50,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/9/98/BTNMeatWagon.png/revision/latest?cb=20090112014249',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ud_crypt_fiend',
    name: 'Crypt Fiend',
    race: Race.Undead,
    type: CardType.Unit,
    goldCost: 215,
    woodCost: 40,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/6/66/BTNCryptFiend.png/revision/latest?cb=20090111235916',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ud_gargoyle',
    name: 'Gargoyle',
    race: Race.Undead,
    type: CardType.Unit,
    goldCost: 175,
    woodCost: 30,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/8/8e/BTNGargoyle.png/revision/latest?cb=20090112004152',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ud_banshee',
    name: 'Banshee',
    race: Race.Undead,
    type: CardType.Unit,
    goldCost: 155,
    woodCost: 30,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/6/65/BTNBanshee.png/revision/latest?cb=20090111213414',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ud_necromancer',
    name: 'Necromancer',
    race: Race.Undead,
    type: CardType.Unit,
    goldCost: 145,
    woodCost: 20,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/f/f6/BTNNecromancer.png/revision/latest?cb=20090112014643',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ud_obsidian_statue',
    name: 'Obsidian Statue',
    race: Race.Undead,
    type: CardType.Unit,
    goldCost: 200,
    woodCost: 35,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/c/c4/BTNObsidianStatue.png/revision/latest?cb=20090112035101',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ud_frost_wyrm',
    name: 'Frost Wyrm',
    race: Race.Undead,
    type: CardType.Unit,
    goldCost: 385,
    woodCost: 120,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/2/22/BTNFrostWyrm.png/revision/latest?cb=20090112004033',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
];

export const HU_UNITS: Card[] = [
  {
    id: 'hu_peasant',
    name: 'Peasant',
    race: Race.Human,
    type: CardType.Unit,
    goldCost: 75,
    woodCost: 0,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/b/bc/BTNPeasant.png/revision/latest?cb=20090112015133',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'hu_footman',
    name: 'Footman',
    race: Race.Human,
    type: CardType.Unit,
    goldCost: 135,
    woodCost: 0,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/6/66/BTNFootman.png/revision/latest?cb=20090112003808',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'hu_knight',
    name: 'Knight',
    race: Race.Human,
    type: CardType.Unit,
    goldCost: 245,
    woodCost: 60,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/9/97/BTNKnight.png/revision/latest?cb=20090112013608',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'hu_rifleman',
    name: 'Rifleman',
    race: Race.Human,
    type: CardType.Unit,
    goldCost: 205,
    woodCost: 30,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/1/1c/BTNRifleman.png/revision/latest?cb=20090112020305',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'hu_mortar_team',
    name: 'Mortar Team',
    race: Race.Human,
    type: CardType.Unit,
    goldCost: 180,
    woodCost: 70,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/2/20/BTNMortarTeam.png/revision/latest?cb=20090112014503',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'hu_flying_machine',
    name: 'Flying Machine',
    race: Race.Human,
    type: CardType.Unit,
    goldCost: 100,
    woodCost: 30,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/7/72/BTNFlyingMachine.png/revision/latest?cb=20090112033132',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'hu_gryphon_rider',
    name: 'Gryphon Rider',
    race: Race.Human,
    type: CardType.Unit,
    goldCost: 280,
    woodCost: 70,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/4/47/BTNGryphonRider.png/revision/latest?cb=20090112004822',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'hu_priest',
    name: 'Priest',
    race: Race.Human,
    type: CardType.Unit,
    goldCost: 135,
    woodCost: 10,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/6/69/BTNPriest.png/revision/latest?cb=20100117215023',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'hu_sorceress',
    name: 'Sorceress',
    race: Race.Human,
    type: CardType.Unit,
    goldCost: 155,
    woodCost: 20,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/0/05/BTNSorceress.png/revision/latest?cb=20090112021500',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'hu_siege_engine',
    name: 'Siege Engine',
    race: Race.Human,
    type: CardType.Unit,
    goldCost: 195,
    woodCost: 60,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/4/46/BTNSeigeEngine.png/revision/latest?cb=20090112040444',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'hu_spell_breaker',
    name: 'Spell Breaker',
    race: Race.Human,
    type: CardType.Unit,
    goldCost: 215,
    woodCost: 30,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/d/dc/BTNSpellBreaker.png/revision/latest?cb=20090112040838',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'hu_dragonhawk_rider',
    name: 'Dragonhawk Rider',
    race: Race.Human,
    type: CardType.Unit,
    goldCost: 200,
    woodCost: 30,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/9/97/BTNDragonHawk.png/revision/latest?cb=20090112000908',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
];

export const NE_UNITS: Card[] = [
  {
    id: 'ne_wisp',
    name: 'Wisp',
    race: Race.NightElf,
    type: CardType.Unit,
    goldCost: 60,
    woodCost: 0,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/a/a8/BTNWisp.png/revision/latest?cb=20090112023517',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ne_archer',
    name: 'Archer',
    race: Race.NightElf,
    type: CardType.Unit,
    goldCost: 130,
    woodCost: 10,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/e/ee/BTNArcher.png/revision/latest?cb=20090111201932',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ne_huntress',
    name: 'Huntress',
    race: Race.NightElf,
    type: CardType.Unit,
    goldCost: 195,
    woodCost: 20,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/2/24/BTNHuntress.png/revision/latest?cb=20090112005859',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ne_dryad',
    name: 'Dryad',
    race: Race.NightElf,
    type: CardType.Unit,
    goldCost: 145,
    woodCost: 60,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/7/74/BTNDryad.png/revision/latest?cb=20090112001005',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ne_glaive_thrower',
    name: 'Glaive Thrower',
    race: Race.NightElf,
    type: CardType.Unit,
    goldCost: 210,
    woodCost: 65,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/7/77/BTNGlaiveThrower.png/revision/latest?cb=20090112033345',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ne_hippogryph',
    name: 'Hippogryph',
    race: Race.NightElf,
    type: CardType.Unit,
    goldCost: 160,
    woodCost: 20,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/8/8d/BTNHippogriff.png/revision/latest?cb=20090112005442',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ne_chimaera',
    name: 'Chimaera',
    race: Race.NightElf,
    type: CardType.Unit,
    goldCost: 330,
    woodCost: 70,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/5/5c/BTNChimaera.png/revision/latest?cb=20090111223932',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ne_druid_of_the_talon',
    name: 'Druid of the Talon',
    race: Race.NightElf,
    type: CardType.Unit,
    goldCost: 135,
    woodCost: 20,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/e/ed/BTNDruidOfTheTalon.png/revision/latest?cb=20090112000942',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ne_druid_of_the_claw',
    name: 'Druid of the Claw',
    race: Race.NightElf,
    type: CardType.Unit,
    goldCost: 255,
    woodCost: 80,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/9/91/BTNDruidOfTheClaw.png/revision/latest?cb=20090112000931',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ne_mountain_giant',
    name: 'Mountain Giant',
    race: Race.NightElf,
    type: CardType.Unit,
    goldCost: 350,
    woodCost: 100,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/7/7c/BTNMountainGiant.png/revision/latest?cb=20090112034600',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'ne_faerie_dragon',
    name: 'Faerie Dragon',
    race: Race.NightElf,
    type: CardType.Unit,
    goldCost: 155,
    woodCost: 25,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/0/0b/BTNFaerieDragon.png/revision/latest?cb=20090112032823',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
];

export const OC_UNITS: Card[] = [
  {
    id: 'oc_peon',
    name: 'Peon',
    race: Race.Orc,
    type: CardType.Unit,
    goldCost: 75,
    woodCost: 0,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/f/f6/BTNPeon.png/revision/latest?cb=20090112015218',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'oc_grunt',
    name: 'Grunt',
    race: Race.Orc,
    type: CardType.Unit,
    goldCost: 200,
    woodCost: 0,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/f/fa/BTNGrunt.png/revision/latest?cb=20090112004800',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'oc_raider',
    name: 'Raider',
    race: Race.Orc,
    type: CardType.Unit,
    goldCost: 180,
    woodCost: 40,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/e/e9/BTNRaider.png/revision/latest?cb=20090112015708',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'oc_tauren_warrior',
    name: 'Tauren Warrior',
    race: Race.Orc,
    type: CardType.Unit,
    goldCost: 280,
    woodCost: 80,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/8/82/BTNTauren.png/revision/latest?cb=20090112022142',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'oc_troll_headhunter',
    name: 'Troll Headhunter',
    race: Race.Orc,
    type: CardType.Unit,
    goldCost: 140,
    woodCost: 20,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/4/42/BTNHeadhunter.png/revision/latest?cb=20110523182155',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'oc_demolisher',
    name: 'Demolisher',
    race: Race.Orc,
    type: CardType.Unit,
    goldCost: 220,
    woodCost: 50,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/d/d3/BTNDemolisher.png/revision/latest?cb=20090111204922',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'oc_kodo_beast',
    name: 'Kodo Beast',
    race: Race.Orc,
    type: CardType.Unit,
    goldCost: 255,
    woodCost: 60,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/9/9f/BTNKotoBeast.png/revision/latest?cb=20090112013641',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'oc_wind_rider',
    name: 'Wind Rider',
    race: Race.Orc,
    type: CardType.Unit,
    goldCost: 265,
    woodCost: 40,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/2/2f/BTNWyvernRider.png/revision/latest?cb=20090112023709',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'oc_troll_batrider',
    name: 'Troll Batrider',
    race: Race.Orc,
    type: CardType.Unit,
    goldCost: 160,
    woodCost: 40,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/7/77/BTNTrollBatRider.png/revision/latest?cb=20090112041840',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'oc_troll_witch_doctor',
    name: 'Troll Witch Doctor',
    race: Race.Orc,
    type: CardType.Unit,
    goldCost: 145,
    woodCost: 25,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/6/68/BTNWitchDoctor.png/revision/latest?cb=20090112023602',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'oc_shaman',
    name: 'Shaman',
    race: Race.Orc,
    type: CardType.Unit,
    goldCost: 130,
    woodCost: 20,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/3/3a/BTNShaman.png/revision/latest?cb=20090112021010',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
  {
    id: 'oc_spirit_walker',
    name: 'Spirit Walker',
    race: Race.Orc,
    type: CardType.Unit,
    goldCost: 195,
    woodCost: 35,
    imagePath: 'https://static.wikia.nocookie.net/wowpedia/images/5/50/BTNSpiritWalker.png/revision/latest?cb=20090112041051',
    difficulty: [Difficulty.Medium, Difficulty.Hard],
  },
];